apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alertmanager-webhook
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        url: "{{ .webhook_url }}"
  data:
    - secretKey: webhook_url
      remoteRef:
        key: lla-rke2-cs2/monitoring/alertmanager-webhook
